### ISSUE TITLE
Parallel threads accessing class instances results in "IllegalInstanceIDException: Compressed ID is not valid"

### ISSUE THREAD

**Issue by sadaaithal** [aragozin/heaplib#5]
I am using heap-cli jar.
In one of the use cases I have to parse all objects of about 10 classes. 
Doing this on hprofs of > 10gb is taking quite a lot of time.
So I tried spinning off different threads for each of the JavaClass ( about 10 threads) 

And then I start seeing exceptions like this:

org.netbeans.lib.profiler.heap.IllegalInstanceIDException: Compressed ID is not valid: 2656261811 ID: 21250094488
	at org.netbeans.lib.profiler.heap.HeapOffsetMap.offsetForCompressed(HeapOffsetMap.java:126)
	at org.netbeans.lib.profiler.heap.HeapOffsetMap.offset(HeapOffsetMap.java:79)
	at org.netbeans.lib.profiler.heap.FastHprofHeap.idToDumpOffset(FastHprofHeap.java:98)
	at org.netbeans.lib.profiler.heap.FastHprofHeap.getInstanceByID(FastHprofHeap.java:124)
	at org.netbeans.lib.profiler.heap.ObjectArrayLazyList.get(ObjectArrayLazyList.java:51)
	at org.netbeans.lib.profiler.heap.ObjectArrayLazyList.get(ObjectArrayLazyList.java:29)
	at java.util.AbstractList$Itr.next(AbstractList.java:358)
	at DISHadoopFSCacheParser.getHeapInstancesOfClass(DISHadoopFSCacheParser.java:219)
	at java.lang.Thread.run(Thread.java:748)

I am trying to understand the FastHprofHeap functioning.
But is there a way work around this? ( like prepare the compressed offset map beforehand)

**Comment by aragozin** [comment]
Library is single threaded. Provided that heap processing IO bound, not CPU bound, investing in multi threading has little value in my view.
Instead of 10 threads, I suggest you to investigate options to process 10 classes in on pass in single thread. Linear scan of heap has advantage of data locality and sequential IO.

**Comment by sadaaithal** [comment]
Thank you. I am now performing a single pass of all instances of the heap as you suggested. 
It is also faster than the earlier approach.
